'use client';

import { useRef, useState } from 'react';
import { MatrixRain } from '../components/matrix-rain';
import { TickerBar } from '../components/ticker-bar';
import { StatusBar } from '../components/status-bar';
import { Terminal, type Rank, type TerminalHandle, type VerdictView } from '../components/terminal';
import { WalletCarousel } from '../components/wallet-carousel';
import { IntelPanel } from '../components/intel-panel';
import { InspectorPanel } from '../components/inspector-panel';
import { BannerHeader } from '../components/banner-header';
import { PasteBar } from '../components/paste-bar';

const CLAUDE_AMBER = '#ffab00';

export default function Home() {
  const [scans, setScans] = useState(0);
  const [rank, setRank] = useState<Rank>('NOVICE');
  const [verdict, setVerdict] = useState<VerdictView | null>(null);
  const terminalRef = useRef<TerminalHandle>(null);

  return (
    <>
      <MatrixRain opacity={0.12} />
      <div className="scanline" aria-hidden />

      <div className="relative z-10 flex flex-col h-screen">
        <TopBar />
        <TickerBar />

        <div className="flex-1 min-h-0 flex bg-panel/20">
          <IntelPanel onChip={(cmd) => terminalRef.current?.execute(cmd)} />
          <div className="flex-1 min-w-0 flex flex-col">
            <BannerHeader />
            <PasteBar onAnalyze={(cmd) => terminalRef.current?.execute(cmd)} />
            <div className="flex-1 min-h-0">
              <Terminal
                ref={terminalRef}
                onScansChange={setScans}
                onRankChange={setRank}
                onVerdict={setVerdict}
              />
            </div>
          </div>
          <InspectorPanel verdict={verdict} />
        </div>

        <div className="hidden sm:block">
          <WalletCarousel />
        </div>

        <StatusBar scans={scans} rank={rank} />
      </div>
    </>
  );
}

function TopBar() {
  return (
    <nav className="flex items-center justify-between px-4 sm:px-8 py-2.5 border-b border-neon-green/20 bg-bg/85 backdrop-blur-md">
      <div className="flex items-center gap-3">
        <div className="w-6 h-6 border border-neon-green flex items-center justify-center text-neon-green text-xs font-bold">
          ∆
        </div>
        <span className="text-sm tracking-[0.25em] text-neon-green font-bold">SOLSHIELD</span>
        <span className="text-[10px] tracking-[0.15em] text-dim hidden sm:inline">
          [ v0.1.0-alpha ]
        </span>
      </div>
      <div className="flex items-center gap-4 sm:gap-5 text-[11px] tracking-[0.2em] uppercase">
        <span
          className="hidden md:inline-flex items-center gap-1.5 text-neon-amber/90"
          title="every verdict is generated by Claude (Haiku 4.5 + Opus 4.7), built by 0xnullpavel"
        >
          <span style={{ color: CLAUDE_AMBER }} aria-hidden>
            ✦
          </span>
          <span>powered by claude</span>
          <span className="text-dim">+</span>
          <a
            href="https://github.com/0xnullpavel"
            target="_blank"
            rel="noopener noreferrer"
            className="text-neon-amber/90 hover:text-neon-amber"
          >
            0xnullpavel
          </a>
        </span>
        <a
          href="https://github.com/0xnullpavel/solshield"
          className="text-mute hover:text-neon-cyan transition-colors"
          target="_blank"
          rel="noopener noreferrer"
        >
          [ github ]
        </a>
        <span className="flex items-center gap-1.5 text-neon-green">
          <span className="w-1.5 h-1.5 rounded-full bg-neon-green animate-pulse" />
          <span className="hidden sm:inline">ONLINE</span>
        </span>
      </div>
    </nav>
  );
}
